# http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# Skipping commits with particular message
skip_commits:
  message: /\[ci skip\]/

# environment variables
environment:
  matrix:
  - nodejs_version: 4.0
  - nodejs_version: 4.1
  - nodejs_version: 4.2
  - nodejs_version: 4.3
  - nodejs_version: 5.0
  - nodejs_version: 5.1
  - nodejs_version: 5.2
  - nodejs_version: 5.3
  - nodejs_version: 5.4
  - nodejs_version: 5.5
  - nodejs_version: 5.6
  - nodejs_version: node

# scripts that run after cloning repository
install:
  - ps: Install-Product node $env:nodejs_version
  - git submodule update --init --recursive
  - npm install

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# scripts to run before tests
before_test:
  - node --version
  - npm --version

# to run your custom scripts instead of automatic tests
test_script:
  - npm test
